# Generated by Django 4.2 on 2023-09-19 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=254)),
                ('role', models.CharField(max_length=254)),
                ('date_applied', models.DateField()),
                ('followed_up', models.BigIntegerField()),
                ('rejected', models.CharField(max_length=254)),
                ('req_number', models.CharField(max_length=254)),
                ('recruiter', models.CharField(max_length=254)),
                ('recruiter_email', models.EmailField(max_length=254)),
                ('referral', models.CharField(max_length=254)),
                ('referral_email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=254)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobhunt.jobs')),
            ],
        ),
    ]
