# Generated by Django 4.2.6 on 2023-12-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt', '0002_alter_jobs_date_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='portal_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
