# Generated by Django 4.2.6 on 2023-12-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt', '0003_jobs_portal_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='recruiter',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interviews',
            name='round',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
