# Generated by Django 4.2.6 on 2023-12-20 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt', '0005_remove_interviews_job_interviews_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviews',
            name='recruiter',
        ),
    ]
