# Generated by Django 4.2.6 on 2024-01-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt', '0006_remove_interviews_recruiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviews',
            name='job_id',
        ),
        migrations.AddField(
            model_name='interviews',
            name='company',
            field=models.CharField(default='unknown', max_length=254),
        ),
        migrations.AddField(
            model_name='interviews',
            name='recruiter',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='interviews',
            name='recruiter_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='interviews',
            name='role',
            field=models.CharField(blank=True, default='unknown', max_length=254),
        ),
    ]
